### PR TITLE
First IHEC release

### PR DESCRIPTION
**Pull request by emi80**
This pull request is the base for the first IHEC release. The workflow has been updated to reflect IHEC recommendations and the documentation has been restructured to include instruction on running the pipeline for IHEC integrative analyses.

As the pull request is approved we should probably create a version tag and update the setup document accordingly.

### CODE REVIEW

**Comment by sitag** [comment]
Hi, Emilio

https://github.com/guigolab/grape-nf/blob/IHEC/ihec-setup.md is pointing to master for repository when it pulls the code and not the IHEC branch. We will need to edit this after we make the tag.

**Comment by sitag** [comment]
@emi80 

Quantification task is still running out of resources. I think you changed the memory requirements, but not the time and #cpus. Can you just note this issue in the readme and others may still run into it. Meanwhile I will change the resources to see if it goes through now.

I thought the plan was that you would tag under guigolab repository, and then this repo will just have the readme. Anyway, let's just wrap this up now.

**Comment by emi80** [comment]
Hi Sita,

I thought the plan has always been to keep a fork of `guigolab/grape-nf` incorporating changes from the IHEC branch from there into master. That's why I changed the setup document to point to the master branch of https://github.com/IHEC/grape-nf. Just let me know if you prefer to only have the readme in this repo and use the IHEC branch under `guigolab` repo instead.

About pipeline resources,  the `time` setting is ignored when using the local executor as we are doing in the IHEC setup. I think the task is most likely failing because of memory. As you suggest, I will note this down in the setup document so that people know how to deal with the error they might eventually get.

Let me know which amount of resources worked for you.

**Comment by sitag** [comment]
The peak_vmem in the trace I emailed was ~68G, is that not the relavant mem value? 62G in https://github.com/guigolab/grape-nf/blob/IHEC/ihec-resources.config#L47 likely caused the error. It also takes 10hr with 8CPUs.  

I suppose you used 62G to allow for 61.7G in peak resident set size. I doubt that's enough slack though - using k as 1024 vs 1000 will easily screw with that.  

There's 200mil reads requirement for IHEC, so all these datasets will be fairly intensive computationally. 

In setup document can you give a full example of the command people will run, e.g. in `nexflow run guigolab/grape-nf -profile ihec ...` from https://github.com/guigolab/grape-nf/tree/IHEC#ihec-data , replace the eliipsis with actual parameters (say fore the config with IHEC MCF10A data, or like you have in the other example), otherwise it's not clear if you want to add in other parameters:

    nexflow -bg run guigolab/grape-nf -profile ihec --index input-files.tsv --genome refs/hg38.AXYM.fa --annotation refs/gencode.v21.annotation.AXYM.gtf --rg-platform ILLUMINA --rg-center-name CRG -resume > pipeline.log
	
So is this the way to run IHEC analysis (no other optional parameters?). What about --paired option? We need to define command lines there - in case someone has SET data? 

We should be explicit with what we want people to run. 

Also, in https://github.com/guigolab/grape-nf/blob/IHEC/ihec-setup.md#troubleshooting , all images can have that transient error, not just that image. 

Let's just merge the whole thing, and get this done with.  Can we wrap it up this week?

**Comment by sitag** [comment]
It looks like nextflow is mounting somethings as read only and erring out. I see:

    sambamba-sort: /projects/da_workspace/DA-370/tmp: Read-only file system

It has essentially picked up $TMPDIR from the environment then mounted it as readonly. How do we fix this?

Also, how do we pass bind parameters explicitly? Can't seem to find anything in nextflow documentation.

**Comment by emi80** [comment]
I updated the documentation and resource configuration. Most of the comments should be addressed in the commits.

About quantification memory, I put `64G` for now as it better fits usual machine configurations (e.g. 8 CPUs, `8G` per CPU). I would test it this way and change it with respect to the test outcome.

About the `--paired-end` option, it is not required as the pipeline detects the data type from the input file. There can be single-end and paired-end data at the same time in the same input file.

I need to reproduce the `TMPDIR` issue and see how to fix that.

Bind parameters for Singularity can be passed via the [singularity scope](https://www.nextflow.io/docs/latest/config.html#config-singularity) in the nextflow configuration file.

**Comment by sitag** [comment]
we can just document unsetting TMPDIR to rule out issues.

**Comment by emi80** [comment]
Sounds OK. Another possibility would be to set the `--tmpdir` command line option of `sambamba sort` to the quantification process working dir (or even make it a pipeline parameter so that the user could change it).

**Comment by sitag** [comment]
merging for pre-release. will deal with whatever may be needed for release.

**Pull request merged**
